version: '3.0'
services:
  web-service:
    build: sudo docker pull suhas8/dockertest:web
    ports:
      - 75:8080
    volumes:
      - web-vol:/usr/src/webapp

  finance-service:
    build: sudo docker pull suhas8/dockertest:latest
    ports:
      - 65:80
    volumes:
      - fin-vol:/usr/src/finapp

  portfolio-service:
    build: sudo docker pull suhas8/dockertest:1.0
    ports:
      - 55:80
    volumes:
      - port-vol:/usr/src/portapp

volumes:
  java-vol:
   driver: local
  
  fin-vol:
   driver: local

  port-vol:
   driver: local
